import type { Bahasa } from "@/lib/bahasa";

/* Teks UI seluruh dasbor karhutla per bahasa — satu sumber kebenaran untuk
   semua modul di folder ini (komposer, postingan, lembar komentar, dll.).
   Bagian yang tak dipakai modul tertentu tetap ada di sini supaya pemakainya
   cukup satu objek. */
export const TEKS = {
  id: {
    // Judul penuh halaman — dipakai H1 sr-only; judul pendek + tombol lapor
    // kini milik <Nav gelap> yang dipakai bersama halaman index.
    judul: "Kebakaran Hutan dan Lahan",
    cariLaporan: "Lapor apa yang kamu lihat",
    lokasi: "Kalimantan Barat",
    lokasiOtomatis: "secara otomatis dibaca lokasi",
    lokasiTerdeteksi: "lokasi terdeteksi",
    lokasiDicari: "lokasi dicari",
    cariLokasiCuaca: "Cari kota/provinsi...",
    cariLokasiCuacaAria: "Cari lokasi cuaca",
    deteksiGpsCuacaAria: "Deteksi lokasi cuaca via GPS",
    batalCariCuaca: "Batal cari lokasi cuaca",
    petaJudul: "Aerosol Karhutla",
    petaAngin: "Angin dan kualitas udara",
    petaWaktu: "8 Sep, 00:00 WIB",
    petaLegenda: "Kepekatan aerosol asap kebakaran, dibaca dari satelit Sentinel-5P.",
    petaTipis: "Tipis",
    petaPekat: "Pekat",
    kaki: "Laporan warga terkurasi sebelum ditampilkan. Menyaksikan kebakaran atau dampak asapnya? Ceritakan di kotak laporan.",
    merek: "©2026 Lapor Karhutla",
    hasilKosong: "Tidak ada laporan yang cocok. Coba kata lain, atau kirim laporanmu sendiri.",
    saringanKosong: "Tidak ada laporan pada wilayah atau rentang tanggal ini.",
    hapusSaringan: "Hapus saringan",
    semuaWilayah: "Semua wilayah",
    saringanPilihWilayah: "Pilih wilayah pulau",
    saringanSatuan: "laporan",
    urutan: "Urutan laporan",
    tanggalPanjang: "Pilih rentang tanggal",
    tanggalPendek: "Tanggal",
    urutTerbaru: "Terbaru",
    urutKomentar: "Komentar terbanyak",
    umpan: "Laporan warga",
    situasi: "Panel situasi",
    mainkan: "Mainkan rekaman sebaran",
    tulis: "Apa yang terjadi di sekitarmu?",
    kirim: "Kirim",
    lampirFoto: "Lampirkan foto",
    lampirVideo: "Lampirkan video",
    tandaiLokasi: "Tandai lokasi",
    judulPh: "Judul singkat laporannya",
    ceritaPh: "Ceritakan yang kamu lihat…",
    judulWajib: "Isi judul singkat dulu.",
    ceritaWajib: "Ceritakan kejadiannya sedikit.",
    berkasWajib: "Sertakan minimal satu foto atau video.",
    lokasiOk: "Lokasi ditandai",
    lokasiGagal: "Lokasi gagal dibaca.",
    mencariLokasi: "Mencari…",
    terkirim: "Laporan terkirim.",
    terkirimIsi: "Terima kasih — laporanmu sedang diverifikasi dan akan tampil di beranda setelah lolos kurasi.",
    tulisLagi: "Tulis lagi",
    batal: "Batal",
    mengirim: "Mengirim…",
    memverifikasi: "Memverifikasi…",
    keamananGagal: "Pemeriksaan keamanan gagal dimuat. Periksa koneksi lalu coba lagi.",
    terlaluBanyak: "Maksimal 6 berkas per laporan.",
    terlaluBesar: "Total berkas terlalu besar.",
    suhuMenunggu: "Suhu sedang dimuat",
    bukaPetaSelayar: "Buka peta selayar",
    tutupPetaSelayar: "Tutup peta selayar",
    namaPh: "Nama (opsional)",
    anonim: "Anonim",
    lokasiHapus: "Hapus lokasi",
    wajibMedia: "Foto/video wajib",
    latPh: "Lat",
    lngPh: "Lng",
    tabBeranda: "Beranda",
    tabCari: "Cari laporan",
    tabTulis: "Tulis laporan",
    tabLapor: "Formulir lapor",
    tabPanel: "Buka panel situasi",
    tabUmpan: "Buka daftar laporan",
    videoBisu: "Nyalakan suara video",
    videoSenyap: "Bisukan video",
    videoUlang: "Putar ulang video",
    galeriSebelumnya: "Foto sebelumnya",
    galeriBerikutnya: "Foto berikutnya",
    postingan: "Postingan",
    kembali: "Kembali",
    suka: "Suka",
    komentar: "Komentar",
    selengkapnya: "selengkapnya",
    lebihSedikit: "lebih sedikit",
    lembarBagikan: "Bagikan",
    lembarTersalin: "Tautan tersalin",
  },
  en: {
    judul: "Forest and Land Fires",
    cariLaporan: "Report what you see",
    lokasi: "West Kalimantan",
    lokasiOtomatis: "location read automatically",
    lokasiTerdeteksi: "detected location",
    lokasiDicari: "searched location",
    cariLokasiCuaca: "Search city/province...",
    cariLokasiCuacaAria: "Search weather location",
    deteksiGpsCuacaAria: "Detect weather location via GPS",
    batalCariCuaca: "Cancel weather location search",
    petaJudul: "Wildfire Aerosol",
    petaAngin: "Wind and air quality",
    petaWaktu: "8 Sep, 00:00 WIB",
    petaLegenda: "Smoke aerosol density, read from the Sentinel-5P satellite.",
    petaTipis: "Thin",
    petaPekat: "Dense",
    kaki: "Citizen reports are curated before they appear. Seeing a fire or its haze? Tell us in the report box.",
    merek: "©2026 Lapor Karhutla",
    hasilKosong: "No reports match that. Try other words, or send a report of your own.",
    saringanKosong: "No reports in this region or date range.",
    hapusSaringan: "Clear filters",
    semuaWilayah: "All regions",
    saringanPilihWilayah: "Choose an island region",
    saringanSatuan: "reports",
    urutan: "Report order",
    tanggalPanjang: "Choose a date range",
    tanggalPendek: "Dates",
    urutTerbaru: "Newest",
    urutKomentar: "Most commented",
    umpan: "Citizen reports",
    situasi: "Situation panel",
    mainkan: "Play the spread recording",
    tulis: "What's happening around you?",
    kirim: "Post",
    lampirFoto: "Attach a photo",
    lampirVideo: "Attach a video",
    tandaiLokasi: "Tag location",
    judulPh: "Short report title",
    ceritaPh: "Describe what you see…",
    judulWajib: "Give it a short title first.",
    ceritaWajib: "Describe what happened, briefly.",
    berkasWajib: "Attach at least one photo or video.",
    lokasiOk: "Location tagged",
    lokasiGagal: "Could not read location.",
    mencariLokasi: "Locating…",
    terkirim: "Report sent.",
    terkirimIsi: "Thank you — your report is being verified and will appear on the homepage once approved.",
    tulisLagi: "Write another",
    batal: "Cancel",
    mengirim: "Sending…",
    memverifikasi: "Verifying…",
    keamananGagal: "Security check could not load. Check your connection and try again.",
    terlaluBanyak: "Maximum 6 files per report.",
    terlaluBesar: "Total files too large.",
    suhuMenunggu: "Loading temperature",
    bukaPetaSelayar: "Open fullscreen map",
    tutupPetaSelayar: "Close fullscreen map",
    namaPh: "Name (optional)",
    anonim: "Anonymous",
    lokasiHapus: "Clear location",
    wajibMedia: "Photo/video required",
    latPh: "Lat",
    lngPh: "Lng",
    tabBeranda: "Home",
    tabCari: "Search reports",
    tabTulis: "Write report",
    tabLapor: "Report form",
    tabPanel: "Open situation panel",
    tabUmpan: "Open report list",
    videoBisu: "Unmute video",
    videoSenyap: "Mute video",
    videoUlang: "Replay video",
    galeriSebelumnya: "Previous photo",
    galeriBerikutnya: "Next photo",
    postingan: "Post",
    kembali: "Back",
    suka: "Like",
    komentar: "Comments",
    selengkapnya: "more",
    lebihSedikit: "less",
    lembarBagikan: "Share",
    lembarTersalin: "Link copied",
  },
} satisfies Record<Bahasa, Record<string, string>>;

export type Teks = (typeof TEKS)[Bahasa];